repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
      exclude: ^src/
    - id: check-ast
      exclude: ^src/
    - id: debug-statements
      exclude: ^src/
    - id: check-added-large-files
#    - id: requirements-txt-fixer
    - id: file-contents-sorter
      exclude: ^src/

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
