event_core_fields = {
    'field': [
        "eventID",
        "eventDate",
        "decimalLatitude",
        "decimalLongitude",
        "countryCode",
        "geodeticDatum"],
    'Required or recommended': [
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field"],
}

occurrence_extension_fields = {
    'field': [
        "eventID",
        "occurrenceID",
        "basisOfRecord",
        "scientificName",
        "scientificNameID",
        "kingdom",
        "occurrenceStatus"],
    'Required or recommended': [
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field"],
}

extended_measurement_or_fact_extension_fields = {
    "field": [
        "measurementID",
        "eventID",
        "occurrenceID",
        "measurementType",
        "measurementTypeID",
        "measurementValue",
        "measurementValueID",
        "measurementAccuracy",
        "measurementUnit",
        "measurementUnitID",
        "measurementDeterminedDate",
        "measurementDeterminedBy",
        "measurementMethod",
        "measurementRemarks"
    ],

    "Required or recommended": [
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
    ],
}

occurrence_core_fields = {
    'field': [
        "occurrenceID",
        "basisOfRecord",
        "scientificName",
        "scientificNameID",
        "eventDate",
        "decimalLatitude",
        "decimalLongitude",
        "occurrenceStatus",
        "countryCode",
        "kingdom",
        "geodeticDatum",
        "minimumDepthInMeters",
        "maximumDepthInMeters",
        "coordinateUncertaintyInMeters",
        "samplingProtocol",
        "taxonRank",
        "organismQuantity",
        "organismQuantityType",
        "datasetName",
        "dataGeneralizations",
        "informationWithheld",
        "institutionCode",
    ],
    'Required or recommended': [
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Required field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
        "Recommended field",
    ],
}

